# Generated by Django 5.0.7 on 2025-05-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0002_reclamacao_denuncias_count_denuncia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
