# Generated by Django 5.0.7 on 2025-05-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0003_empresa_publicar'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamacao',
            name='bloquear',
            field=models.BooleanField(default=False),
        ),
    ]
