# Generated by Django 5.0.7 on 2025-05-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0005_empresa_rejeitar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='publicar',
        ),
        migrations.AddField(
            model_name='empresa',
            name='aprovar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rejeitar',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
