# Generated by Django 5.0.7 on 2025-05-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0006_remove_empresa_publicar_empresa_aprovar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='aprovar',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
